version: '3.8'

services:
  ar-glasses-server:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - docker.env
    volumes:
      - ./debug_json_output:/app/debug_json_output
      - ./recorded_audio:/app/recorded_audio
      - ./speakers.db:/app/speakers.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
